/*
  AUTOGENERATED FILE - DO NOT EDIT IT MANUALLY
*/

#include <stdint.h>



#ifndef _LED_MODEL_H_
#define _LED_MODEL_H_

extern const int n_led_curves;

uint32_t calc_duty_cycle(const uint32_t dc_min, const uint32_t dc_max,
                         const uint32_t n_curve, const uint16_t voltage);

#endif
