/*
  AUTOGENERATED FILE - DO NOT EDIT IT MANUALLY
*/

#include <stdint.h>



#include "ledcurve.h"

// main array of times, 80 entries
static const uint16_t led_curve_data[] =
  {  1802,  1798,  1797,  1797,  1796,  1796,  1796,  1796,  1796,     0,
    1816,  1806,  1802,  1800,  1799,  1798,  1798,  1798,  1797,     0,
    1866,  1831,  1819,  1813,  1809,  1807,  1805,  1804,  1803,     0,
    2010,  1902,  1866,  1849,  1838,  1831,  1826,  1822,  1819,     0,
    2511,  2153,  2034,  1974,  1938,  1914,  1897,  1884,  1874,     0,
    3943,  2869,  2511,  2332,  2225,  2153,  2102,  2063,  2034,     0,
    8956,  5375,  4182,  3585,  3227,  2988,  2818,  2690,  2591,     0,
   23277, 12536,  8956,  7165,  6091,  5375,  4864,  4480,  4182,     0 };

// number of messages
const int n_led_curves = 8;

// pointers into the array above corresponding to curves for a particular
// charge
static const uint16_t * const led_curves[] =
  {   led_curve_data +    0   // 1.00e-9 C
    , led_curve_data +   10   // 3.00e-9 C
    , led_curve_data +   20   // 1.00e-8 C
    , led_curve_data +   30   // 3.00e-8 C
    , led_curve_data +   40   // 1.00e-7 C
    , led_curve_data +   50   // 3.00e-7 C
    , led_curve_data +   60   // 1.00e-6 C
    , led_curve_data +   70   // 3.00e-6 C
    };

uint32_t calc_duty_cycle(const uint32_t dc_min, const uint32_t dc_max,
                         const uint32_t n_curve, const uint16_t voltage)
{
  // if we don't have a sane battery voltage, turn on full
  // power and bail early.
  if (voltage == 0)
    {
      return(dc_max);
    }

  uint32_t i_curve = n_curve;
  if (i_curve >= n_led_curves)
    {
      i_curve = n_led_curves - 1;
    }

  uint32_t i, dc;
  for(dc = dc_min, i = 0; dc <= dc_max; dc++, i++)
    {
      const uint16_t threshold = led_curves[i_curve][i];
  
      if (threshold == 0 || threshold <= voltage)
        {
          break;
        }
    }

   return(dc);
}
